"""initial_schema

Revision ID: 076af706dcce
Revises: 
Create Date: 2026-06-21 13:27:42.026892
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076af706dcce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_marca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('log_auditoria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=True),
    sa.Column('ator_id', sa.String(length=36), nullable=True),
    sa.Column('ator_nome', sa.String(length=200), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('entidade', sa.String(length=100), nullable=True),
    sa.Column('entidade_id', sa.String(length=36), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_acao', 'log_auditoria', ['acao'], unique=False)
    op.create_index('ix_audit_ator', 'log_auditoria', ['ator_id'], unique=False)
    op.create_index('ix_audit_data', 'log_auditoria', ['created_at'], unique=False)
    op.create_index('ix_audit_loja', 'log_auditoria', ['loja_id'], unique=False)
    op.create_table('loja',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('verificada', sa.Boolean(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('plano',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_mensal', sa.Float(), nullable=False),
    sa.Column('modulos_incluidos', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('senha_hash', sa.String(length=300), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('papel', sa.Enum('ADMIN_PLATAFORMA', 'GESTOR', 'VENDEDOR', 'CLIENTE', name='papelusuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=100), nullable=True),
    sa.Column('mfa_ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_usuario_email', 'usuario', ['email'], unique=False)
    op.create_table('assinatura',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('plano_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('ATIVA', 'CANCELADA', 'SUSPENSA', 'EXPIRADA', name='statusassinatura'), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plano_id'], ['plano.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assinatura_loja', 'assinatura', ['loja_id'], unique=False)
    op.create_table('catalogo_modelo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['catalogo_marca.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marca_id', 'nome', name='uq_modelo_marca_nome')
    )
    op.create_index('ix_modelo_marca', 'catalogo_modelo', ['marca_id'], unique=False)
    op.create_table('cliente_pf',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('renda_mensal', sa.Float(), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cliente_cpf', 'cliente_pf', ['cpf'], unique=False)
    op.create_index('ix_cliente_loja', 'cliente_pf', ['loja_id'], unique=False)
    op.create_index('ix_cliente_telefone', 'cliente_pf', ['telefone'], unique=False)
    op.create_table('membro_loja',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('papel', sa.Enum('ADMIN_PLATAFORMA', 'GESTOR', 'VENDEDOR', 'CLIENTE', name='papelusuario'), nullable=False),
    sa.Column('modulos', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'loja_id', name='uq_membro_usuario_loja')
    )
    op.create_index('ix_membro_loja_id', 'membro_loja', ['loja_id'], unique=False)
    op.create_table('modulo_habilitado',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('nome_modulo', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loja_id', 'nome_modulo', name='uq_modulo_loja')
    )
    op.create_index('ix_modulo_loja', 'modulo_habilitado', ['loja_id'], unique=False)
    op.create_table('sessao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('revogada', sa.Boolean(), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index('ix_sessao_refresh', 'sessao', ['refresh_token'], unique=False)
    op.create_index('ix_sessao_usuario', 'sessao', ['usuario_id'], unique=False)
    op.create_table('veiculo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=200), nullable=False),
    sa.Column('versao', sa.String(length=200), nullable=True),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=False),
    sa.Column('ano_modelo', sa.Integer(), nullable=False),
    sa.Column('km', sa.Integer(), nullable=True),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('cambio', sa.Enum('MANUAL', 'AUTOMATICO', 'CVT', 'AUTOMATIZADO', name='tipocambio'), nullable=True),
    sa.Column('combustivel', sa.Enum('GASOLINA', 'ETANOL', 'FLEX', 'DIESEL', 'ELETRICO', 'HIBRIDO', 'GNV', name='tipocombustivel'), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('portas', sa.Integer(), nullable=True),
    sa.Column('preco_venda', sa.Float(), nullable=True),
    sa.Column('preco_custo', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DISPONIVEL', 'RESERVADO', 'VENDIDO', 'REPASSE', 'INATIVO', name='statusveiculo'), nullable=False),
    sa.Column('publicado_marketplace', sa.Boolean(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('opcionais', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_veiculo_loja', 'veiculo', ['loja_id'], unique=False)
    op.create_index('ix_veiculo_marca_modelo', 'veiculo', ['marca', 'modelo'], unique=False)
    op.create_index('ix_veiculo_marketplace', 'veiculo', ['publicado_marketplace'], unique=False)
    op.create_index('ix_veiculo_placa', 'veiculo', ['placa'], unique=False)
    op.create_index('ix_veiculo_status', 'veiculo', ['status'], unique=False)
    op.create_table('comissao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('vendedor_id', sa.String(length=36), nullable=True),
    sa.Column('veiculo_id', sa.String(length=36), nullable=True),
    sa.Column('valor_venda', sa.Float(), nullable=False),
    sa.Column('percentual', sa.Float(), nullable=False),
    sa.Column('valor_comissao', sa.Float(), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comissao_loja', 'comissao', ['loja_id'], unique=False)
    op.create_index('ix_comissao_vendedor', 'comissao', ['vendedor_id'], unique=False)
    op.create_table('conversa',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.Enum('B2C', 'B2B', name='tipoconversa'), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=True),
    sa.Column('cliente_id', sa.String(length=36), nullable=True),
    sa.Column('veiculo_id', sa.String(length=36), nullable=True),
    sa.Column('loja_a_id', sa.String(length=36), nullable=True),
    sa.Column('loja_b_id', sa.String(length=36), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loja_a_id'], ['loja.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loja_b_id'], ['loja.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversa_cliente', 'conversa', ['cliente_id'], unique=False)
    op.create_index('ix_conversa_loja', 'conversa', ['loja_id'], unique=False)
    op.create_table('favorito',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('veiculo_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'veiculo_id', name='uq_favorito_usuario_veiculo')
    )
    op.create_index('ix_favorito_usuario', 'favorito', ['usuario_id'], unique=False)
    op.create_index('ix_favorito_veiculo', 'favorito', ['veiculo_id'], unique=False)
    op.create_table('lancamento_financeiro',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.Enum('RECEITA', 'DESPESA', 'COMISSAO', name='tipolancamento'), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('veiculo_id', sa.String(length=36), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lancamento_data', 'lancamento_financeiro', ['data'], unique=False)
    op.create_index('ix_lancamento_loja', 'lancamento_financeiro', ['loja_id'], unique=False)
    op.create_table('lead',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('veiculo_id', sa.String(length=36), nullable=True),
    sa.Column('etapa', sa.Enum('LEAD', 'PROPOSTA', 'NEGOCIACAO', 'FECHAMENTO', 'PERDIDO', name='etapalead'), nullable=False),
    sa.Column('origem', sa.Enum('VITRINE', 'MANUAL', 'SIMULADOR', 'WHATSAPP', name='origemlead'), nullable=False),
    sa.Column('valor_proposta', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente_pf.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_cliente', 'lead', ['cliente_id'], unique=False)
    op.create_index('ix_lead_etapa', 'lead', ['etapa'], unique=False)
    op.create_index('ix_lead_loja', 'lead', ['loja_id'], unique=False)
    op.create_table('midia',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('veiculo_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.Enum('FOTO', 'VIDEO', name='tipomidia'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_midia_veiculo', 'midia', ['veiculo_id'], unique=False)
    op.create_table('pagamento',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assinatura_id', sa.String(length=36), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', 'FALHOU', 'ESTORNADO', name='statuspagamento'), nullable=False),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinatura.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pagamento_assinatura', 'pagamento', ['assinatura_id'], unique=False)
    op.create_table('publicacao_b2b',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('veiculo_id', sa.String(length=36), nullable=True),
    sa.Column('autor_id', sa.String(length=36), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('valor_repasse', sa.Float(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pub_b2b_loja', 'publicacao_b2b', ['loja_id'], unique=False)
    op.create_table('comentario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('publicacao_id', sa.String(length=36), nullable=False),
    sa.Column('autor_id', sa.String(length=36), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publicacao_id'], ['publicacao_b2b.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comentario_pub', 'comentario', ['publicacao_id'], unique=False)
    op.create_table('curtida',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('publicacao_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publicacao_id'], ['publicacao_b2b.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publicacao_id', 'usuario_id', name='uq_curtida_pub_usuario')
    )
    op.create_index('ix_curtida_pub', 'curtida', ['publicacao_id'], unique=False)
    op.create_table('mensagem',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversa_id', sa.String(length=36), nullable=False),
    sa.Column('autor_id', sa.String(length=36), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mensagem_conversa', 'mensagem', ['conversa_id'], unique=False)
    op.create_table('negociacao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('veiculo_id', sa.String(length=36), nullable=True),
    sa.Column('valor_proposta', sa.Float(), nullable=True),
    sa.Column('valor_entrada', sa.Float(), nullable=True),
    sa.Column('parcelas', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_negociacao_lead', 'negociacao', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_negociacao_lead', table_name='negociacao')
    op.drop_table('negociacao')
    op.drop_index('ix_mensagem_conversa', table_name='mensagem')
    op.drop_table('mensagem')
    op.drop_index('ix_curtida_pub', table_name='curtida')
    op.drop_table('curtida')
    op.drop_index('ix_comentario_pub', table_name='comentario')
    op.drop_table('comentario')
    op.drop_index('ix_pub_b2b_loja', table_name='publicacao_b2b')
    op.drop_table('publicacao_b2b')
    op.drop_index('ix_pagamento_assinatura', table_name='pagamento')
    op.drop_table('pagamento')
    op.drop_index('ix_midia_veiculo', table_name='midia')
    op.drop_table('midia')
    op.drop_index('ix_lead_loja', table_name='lead')
    op.drop_index('ix_lead_etapa', table_name='lead')
    op.drop_index('ix_lead_cliente', table_name='lead')
    op.drop_table('lead')
    op.drop_index('ix_lancamento_loja', table_name='lancamento_financeiro')
    op.drop_index('ix_lancamento_data', table_name='lancamento_financeiro')
    op.drop_table('lancamento_financeiro')
    op.drop_index('ix_favorito_veiculo', table_name='favorito')
    op.drop_index('ix_favorito_usuario', table_name='favorito')
    op.drop_table('favorito')
    op.drop_index('ix_conversa_loja', table_name='conversa')
    op.drop_index('ix_conversa_cliente', table_name='conversa')
    op.drop_table('conversa')
    op.drop_index('ix_comissao_vendedor', table_name='comissao')
    op.drop_index('ix_comissao_loja', table_name='comissao')
    op.drop_table('comissao')
    op.drop_index('ix_veiculo_status', table_name='veiculo')
    op.drop_index('ix_veiculo_placa', table_name='veiculo')
    op.drop_index('ix_veiculo_marketplace', table_name='veiculo')
    op.drop_index('ix_veiculo_marca_modelo', table_name='veiculo')
    op.drop_index('ix_veiculo_loja', table_name='veiculo')
    op.drop_table('veiculo')
    op.drop_index('ix_sessao_usuario', table_name='sessao')
    op.drop_index('ix_sessao_refresh', table_name='sessao')
    op.drop_table('sessao')
    op.drop_index('ix_modulo_loja', table_name='modulo_habilitado')
    op.drop_table('modulo_habilitado')
    op.drop_index('ix_membro_loja_id', table_name='membro_loja')
    op.drop_table('membro_loja')
    op.drop_index('ix_cliente_telefone', table_name='cliente_pf')
    op.drop_index('ix_cliente_loja', table_name='cliente_pf')
    op.drop_index('ix_cliente_cpf', table_name='cliente_pf')
    op.drop_table('cliente_pf')
    op.drop_index('ix_modelo_marca', table_name='catalogo_modelo')
    op.drop_table('catalogo_modelo')
    op.drop_index('ix_assinatura_loja', table_name='assinatura')
    op.drop_table('assinatura')
    op.drop_index('ix_usuario_email', table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('plano')
    op.drop_table('loja')
    op.drop_index('ix_audit_loja', table_name='log_auditoria')
    op.drop_index('ix_audit_data', table_name='log_auditoria')
    op.drop_index('ix_audit_ator', table_name='log_auditoria')
    op.drop_index('ix_audit_acao', table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_table('catalogo_marca')
    # ### end Alembic commands ###
