"""add_solicitacao_aprovacao

Revision ID: 0beeb76f1883
Revises: 076af706dcce
Create Date: 2026-06-21 14:55:01.117812
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0beeb76f1883'
down_revision: Union[str, None] = '076af706dcce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacao_aprovacao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('requisitante_id', sa.String(length=36), nullable=False),
    sa.Column('tipo_acao', sa.Enum('EXCLUIR_VEICULO', 'ALTERAR_PRECO', name='tipoacaoaprovacao'), nullable=False),
    sa.Column('entidade_id', sa.String(length=36), nullable=False),
    sa.Column('dados_novos', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', name='statusaprovacao'), nullable=False),
    sa.Column('justificativa_rejeicao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisitante_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_solicitacao_loja', 'solicitacao_aprovacao', ['loja_id'], unique=False)
    op.create_index('ix_solicitacao_status', 'solicitacao_aprovacao', ['status'], unique=False)
    # ### end Alembic commands ###

    # --- RLS (Row Level Security) Condicional para PostgreSQL ---
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TABLE solicitacao_aprovacao ENABLE ROW LEVEL SECURITY;")
        op.execute("""
            CREATE POLICY solicitacao_tenant_isolation ON solicitacao_aprovacao
            FOR ALL
            USING (loja_id = current_setting('app.current_loja_id', true));
        """)
        op.execute("ALTER TABLE veiculo ENABLE ROW LEVEL SECURITY;")
        op.execute("""
            CREATE POLICY veiculo_tenant_isolation ON veiculo
            FOR ALL
            USING (loja_id = current_setting('app.current_loja_id', true));
        """)


def downgrade() -> None:
    # --- RLS (Row Level Security) Condicional para PostgreSQL ---
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP POLICY IF EXISTS solicitacao_tenant_isolation ON solicitacao_aprovacao;")
        op.execute("DROP POLICY IF EXISTS veiculo_tenant_isolation ON veiculo;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_solicitacao_status', table_name='solicitacao_aprovacao')
    op.drop_index('ix_solicitacao_loja', table_name='solicitacao_aprovacao')
    op.drop_table('solicitacao_aprovacao')
    # ### end Alembic commands ###
