"""add_status_pagamento_to_lancamento

Revision ID: 2175ae5b512d
Revises: a1c9e7d04f32
Create Date: 2026-07-01 00:13:47.623767
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2175ae5b512d'
down_revision: Union[str, None] = 'a1c9e7d04f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento_financeiro') as batch_op:
        batch_op.add_column(sa.Column('status_pagamento', sa.Enum('PENDENTE', 'PAGO', 'FALHOU', 'ESTORNADO', name='statuspagamento'), nullable=False, server_default='PAGO'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento_financeiro') as batch_op:
        batch_op.drop_column('status_pagamento')
    # ### end Alembic commands ###
