"""Add simulador de credito tables

Revision ID: 260dc3911295
Revises: d674ee962fac
Create Date: 2026-06-26 19:11:46.492868
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260dc3911295'
down_revision: Union[str, None] = 'd674ee962fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credencial_banco',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('banco', sa.Enum('BV', 'PAN', 'CREDITAS', name='bancosimulador'), nullable=False),
    sa.Column('credenciais_cifradas', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loja_id', 'banco', name='uq_credencial_loja_banco')
    )
    op.create_table('simulacao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('veiculo_id', sa.String(length=36), nullable=True),
    sa.Column('cliente_id', sa.String(length=36), nullable=True),
    sa.Column('criado_por_id', sa.String(length=36), nullable=True),
    sa.Column('entrada', sa.Float(), nullable=False),
    sa.Column('prazo_desejado', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'CONCLUIDA', 'ERRO', name='statussimulacao'), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente_pf.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulacao_resultado',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('simulacao_id', sa.String(length=36), nullable=False),
    sa.Column('banco', sa.Enum('BV', 'PAN', 'CREDITAS', name='bancosimulador'), nullable=False),
    sa.Column('status', sa.Enum('APROVADO', 'NEGADO', 'ERRO', 'MOCK', 'BROWSER', name='statusresultadobanco'), nullable=False),
    sa.Column('parcela', sa.Float(), nullable=True),
    sa.Column('taxa', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('prazo', sa.Integer(), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('tempo_ms', sa.Integer(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['simulacao_id'], ['simulacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulacao_resultado')
    op.drop_table('simulacao')
    op.drop_table('credencial_banco')
    # ### end Alembic commands ###
