"""add_assistente_ia

Revision ID: d5811c6ceda5
Revises: 260dc3911295
Create Date: 2026-06-26 22:41:00.799039
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5811c6ceda5'
down_revision: Union[str, None] = '260dc3911295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistente_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('tom', sa.Enum('FORMAL', 'AMIGAVEL', 'DIRETO', 'CONSULTIVO', 'DESCONTRAIDO', name='tomassistente'), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('estilo_resumo', sa.Text(), nullable=True),
    sa.Column('voz_id', sa.String(length=100), nullable=True),
    sa.Column('consentimento_voz', sa.Boolean(), nullable=False),
    sa.Column('consentimento_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loja_id', 'usuario_id', name='uq_assistente_config_loja_usuario')
    )
    op.create_table('assistente_permissao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('pode_usar', sa.Boolean(), nullable=False),
    sa.Column('autonomia_default', sa.Enum('COPILOTO', 'AUTOMATICO', name='autonomiaassistente'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loja_id', 'usuario_id', name='uq_assistente_permissao_loja_usuario')
    )
    op.create_table('conversa_whatsapp',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('conversa_whatsapp_id', sa.String(length=100), nullable=False),
    sa.Column('contato_nome', sa.String(length=200), nullable=False),
    sa.Column('contato_numero', sa.String(length=50), nullable=False),
    sa.Column('autonomia', sa.Enum('COPILOTO', 'AUTOMATICO', name='autonomiaassistente'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loja_id', 'usuario_id', 'conversa_whatsapp_id', name='uq_conversa_whatsapp_loja_user_jid')
    )
    op.create_table('mensagem_whatsapp',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversa_id', sa.String(length=36), nullable=False),
    sa.Column('mensagem_whatsapp_id', sa.String(length=200), nullable=True),
    sa.Column('autor_tipo', sa.String(length=50), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('midia_url', sa.String(length=500), nullable=True),
    sa.Column('midia_tipo', sa.String(length=50), nullable=True),
    sa.Column('sugestao_ia', sa.Text(), nullable=True),
    sa.Column('enviada_ia', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa_whatsapp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagem_whatsapp')
    op.drop_table('conversa_whatsapp')
    op.drop_table('assistente_permissao')
    op.drop_table('assistente_config')
    # ### end Alembic commands ###
