"""add_proposta_repasse

Revision ID: d674ee962fac
Revises: 0beeb76f1883
Create Date: 2026-06-21 22:07:47.688617
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd674ee962fac'
down_revision: Union[str, None] = '0beeb76f1883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposta_repasse',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loja_proponente_id', sa.String(length=36), nullable=False),
    sa.Column('loja_destino_id', sa.String(length=36), nullable=False),
    sa.Column('veiculo_id', sa.String(length=36), nullable=False),
    sa.Column('valor_proposta', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'ACEITA', 'REJEITADA', 'CANCELADA', name='statuspropostarepasse'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loja_destino_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loja_proponente_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposta_rep_dest', 'proposta_repasse', ['loja_destino_id'], unique=False)
    op.create_index('ix_proposta_rep_prop', 'proposta_repasse', ['loja_proponente_id'], unique=False)
    op.create_index('ix_proposta_rep_veiculo', 'proposta_repasse', ['veiculo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proposta_rep_veiculo', table_name='proposta_repasse')
    op.drop_index('ix_proposta_rep_prop', table_name='proposta_repasse')
    op.drop_index('ix_proposta_rep_dest', table_name='proposta_repasse')
    op.drop_table('proposta_repasse')
    # ### end Alembic commands ###
